version: "3.9"
services:
  kardbot:
    image: tkvarfordt/kardbot:v1.11.0
    container_name: kardbot-v1.11.0
    volumes:
      - ./config:/app/config
      - ./assets/pasta:/app/assets/pasta
      - ./assets/wednesday:/app/assets/wednesday
    environment:
      - KARDBOT_TOKEN=${KARDBOT_TOKEN}
      - KARDBOT_OWNER_ID=${KARDBOT_OWNER_ID}
      - KARDBOT_TESTBED_GUILD=${KARDBOT_TESTBED_GUILD}
      - IMGFLIP_API_USERNAME=${IMGFLIP_API_USERNAME}
      - IMGFLIP_API_PASSWORD=${IMGFLIP_API_PASSWORD}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      - TZ=${TZ}
    restart: unless-stopped
