version: "3.9"
services:
  kardbot:
    image: tkvarfordt/kardbot:v1.3.0-beta
    container_name: kardbot-v1.3.0-beta
    volumes:
      - ./config:/app/config
      - ./assets/pasta:/app/assets/pasta
      - ./assets/wednesday:/app/assets/wednesday
    environment:
      - KARDBOT_TOKEN=${KARDBOT_TOKEN}
      - KARDBOT_OWNER_ID=${KARDBOT_OWNER_ID}
      - KARDBOT_TESTBED_GUILD=${KARDBOT_TESTBED_GUILD}
    restart: unless-stopped
