version: "3.9"
services:
  kardbot:
    image: tkvarfordt/kardbot:v0.0.0-alpha
    container_name: kardbot-v0.0.0-alpha
    volumes:
      - ./config:/app/config
    environment:
      - KARDBOT_TOKEN=${KARDBOT_TOKEN}
      - KARDBOT_OWNER_ID=${KARDBOT_OWNER_ID}
      - KARDBOT_TESTBED_GUILD=${KARDBOT_TESTBED_GUILD}
